export default {
    SET_ERROR: 'SET_ERROR',
    SET_BOOKS: 'SET_BOOKS',
    SET_BOOK_DETAILS: 'SET_BOOK_DETAILS',
    ADD_BOOK: 'ADD_BOOK',
    REMOVE_BOOK: 'REMOVE_BOOK',
    UPDATE_BOOK: 'UPDATE_BOOK',
    ADD_IMG: 'ADD_IMG',
    SET_BOOKSAPI: 'SET_BOOKSAPI',
    SET_BOOKSAPI_DETAILS: 'SET_BOOKSAPI_DETAILS',
    SET_CURRENTBOOK_PAGE: 'SET_CURRENTBOOK_PAGE',
    SET_TOTALBOOKS_PAGES: 'SET_TOTALBOOKS_PAGES',
    SET_BOOKAPI_DETAILS: 'SET_BOOKAPI_DETAILS'
};